Add user login feature files
JankariTech/dolibarr pull request #1
Opened 2020-08-19 04:12 UTC by jasson99

# Instructions
*This is a template to help you make good pull requests. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *only keep the "Fix", "Close" or "New" section*
- *follow the project [contributing guidelines](/.github/CONTRIBUTING.md)*
- *replace the bracket enclosed textswith meaningful informations*

## Description
This PR adds feature files for add users, user login and user logout feature.

2020-08-19 04:16 UTC, swoichha commented on test/acceptance/features/login.feature
> +
Please remove these comments.

2020-08-19 04:18 UTC, Talank reviewed
why a lot of whitespaces? :thinking:

2020-08-19 04:18 UTC, Talank commented on test/acceptance/features/addUsers.feature
> +
a lot of empty lines

2020-08-19 04:18 UTC, jasson99 commented on test/acceptance/features/addUsers.feature
> +    Then the message "This user has no permissions defined" <shouldOrShouldNot> displayed
```suggestion
    Then the message "This user has no permissions defined" <shouldOrShouldNot> be displayed
```

2020-08-19 04:24 UTC, Talank requested changes

2020-08-19 04:24 UTC, Talank commented on test/acceptance/features/addUsers.feature
> +    Then the message <message> should be displayed
```suggestion
    Then the message "<message>" should be displayed
```
I think you need to put `message` in inside the quote as it will be input to the step definition

2020-08-19 04:24 UTC, Talank commented on test/acceptance/features/logout.feature
> +    Given the user "dolibarr" is logged in
```suggestion
    Given the user "dolibarr" has logged in
```

2020-08-19 04:24 UTC, kiranparajuli589 requested changes

2020-08-19 04:24 UTC, kiranparajuli589 commented on .gitignore
> +yarn.lock
remove comment.

2020-08-19 04:24 UTC, kiranparajuli589 commented on test/acceptance/features/addUsers.feature
> +    Given the administrator has logged in using the web UI
```suggestion
    Given the administrator has logged in using the webUI
```

2020-08-19 04:24 UTC, kiranparajuli589 commented on test/acceptance/features/addUsers.feature
> +      | yes           | woman  | should not        |
IMO you can merge these two scenarios into a single `Scenario Outline`

2020-08-19 04:24 UTC, kiranparajuli589 commented on test/acceptance/features/addUsers.feature
> +  @issue
?

2020-08-19 04:24 UTC, kiranparajuli589 commented on test/acceptance/features/addUsers.feature
> +
```suggestion

```

2020-08-19 04:24 UTC, kiranparajuli589 commented on test/acceptance/features/login.feature
> +    Then the user should not be able to login
Add an example in the scenario outline below.

2020-08-19 04:24 UTC, kiranparajuli589 commented on test/acceptance/features/login.feature
> +
?

2020-08-19 04:24 UTC, kiranparajuli589 commented on test/acceptance/features/logout.feature
> +    When the user opens the user profile
```suggestion
    When the user opens the user profile using the webUI
```

2020-08-19 04:24 UTC, kiranparajuli589 commented on test/acceptance/features/addUsers.feature
> +    Given the administrator has logged in using the web UI
```suggestion
    Given the administrator has logged in using the webUI
```

2020-08-19 04:48 UTC, SwikritiT commented on test/acceptance/features/login.feature
> +    Then the user should not be able to login
These two scenarios are different , in empty credentials we don't get the error message whereas error message is displayed in scenario below it.

2020-09-07 04:20 UTC, SwikritiT commented on test/acceptance/features/addUsers.feature
> +      | yes           | woman  | should not        |
These two scenarios should have separate  outlines. The first outline is to check user permission and second one is for username with special character. We have changed the data table of second scenario.

2020-09-23 07:57 UTC, Talank commented on .gitignore
> +
bonus line

2020-09-23 11:41 UTC, HariBhandari07 commented on test/acceptance/pageObjects/listUsersPage.js
> +					var lastName = row['last name'];
use `let` or `const` instead of `var`

2020-09-24 05:26 UTC, kiranparajuli589 commented on test/acceptance/pageObjects/addUsersPage.js
> +						.click(`//select[@id="admin"]/option[.="${administrator}"]`);
using variables for such `xpaths` will rescue you from number of issues in future.

2020-09-24 05:26 UTC, kiranparajuli589 commented on test/acceptance/pageObjects/addUsersPage.js
> +						.click(`//select[@id="gender"]/option[.="${gender}"]`);
same here...

2020-09-24 05:26 UTC, kiranparajuli589 commented on test/acceptance/stepDefinitions/addUsersContext.js
> +const adminPassword = 'password';
you can declare these vars from `nightwatch.conf.js` if you're using them in multiple files so that definition is not duplicated in multiple files!

2020-09-24 05:26 UTC, kiranparajuli589 commented on test/acceptance/stepDefinitions/addUsersContext.js
> +	initialUsers = await getUsers();
IMO, I don't think getting all users is needed for every scenario to be run on beforeScenario. Why would a Scenario like `invalid login` need all users for? :thinking:

2020-09-24 05:48 UTC, Talank commented on test/acceptance/pageObjects/addUsersPage.js
> +						.waitForElementVisible(`//select[@id="admin"]/option[.="${administrator}"]`)
bonus space? :thinking:

2020-09-24 05:48 UTC, Talank commented on test/acceptance/pageObjects/listUsersPage.js
> +			},
```suggestion
                              this.useXpath()
				for (const row of usersList) {
					let login = row['login'];
					let lastName = row['last name'];
					const userDetail = util.format(this.elements.userList.selector, login, lastName);

					await this.waitForElementVisible('@userRow')
						.waitForElementVisible(userDetail);
				}

				return this.useCss();
			},
```
HBT? :thinking:
You do not need the step useXpath() inside loop

2020-09-24 05:48 UTC, Talank commented on test/acceptance/stepDefinitions/addUsersContext.js
> +
extra line

2020-09-25 05:18 UTC, dpakach reviewed
Just small comments. Good work altogether :+1: . The code formatting looks a bit off. See what kind of linting they u see for this project for js files and try to fix accordingly.

2020-09-25 05:18 UTC, dpakach commented on test/acceptance/pageObjects/addUsersPage.js
> +					let password = 'hello123';
Why are these values hard coded. can they not be passed through dataTable.

2020-09-25 05:18 UTC, dpakach commented on test/acceptance/stepDefinitions/addUsersContext.js
> +	return client.page.addUsersPage().adminCreatesUser(datatable);
For given step you can probably use API to create the user.

2020-09-25 05:18 UTC, dpakach commented on test/acceptance/pageObjects/addUsersPage.js
> +						.click('@submitButton');
this part is similar in above function too. try to reuse this bit.

2020-09-25 06:46 UTC, SwikritiT commented on test/acceptance/pageObjects/addUsersPage.js
> +					let password = 'hello123';
fixed

2020-09-25 06:46 UTC, SwikritiT commented on test/acceptance/stepDefinitions/addUsersContext.js
> +	return client.page.addUsersPage().adminCreatesUser(datatable);
resolved

2020-09-25 06:46 UTC, SwikritiT commented on test/acceptance/pageObjects/addUsersPage.js
> +						.click('@submitButton');
resolved

2020-09-25 07:23 UTC, dpakach reviewed
Lgtm, the codestyle is not consistent. Please try to fix that.

2020-09-25 07:23 UTC, dpakach commented on test/acceptance/stepDefinitions/addUsersContext.js
> +			found = false;
```suggestion
		found = false;
		for (const initialuser in initialUsers) {
```

2020-10-08 04:49 UTC, individual-it reviewed
can we close that here?

2020-10-20 03:48 UTC, closed without merging